/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toycathon;
import java.awt.Color;
import java.util.ArrayList;
import java.io.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Paarkavi Saravanan
 */
public class z_words_level2 extends javax.swing.JFrame {
    z_audio a=new z_audio();
    MatteBorder b= BorderFactory.createMatteBorder(5,5,5,5,Color.red);
    z_logic obj=new z_logic();
    ArrayList<String> C = new ArrayList<String>();
    
    int count=0;
    
    {
    try
    {
    FileInputStream rd=new FileInputStream("StoreE");
    ObjectInputStream rr=new ObjectInputStream(rd);
    C=(ArrayList<String>)rr.readObject();
    rr.close();
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    }
    
    public void working2(String s)
    {
        count++;
        if(count==1)
        {
            if(C.get(0).equals(s))
            {
            obj.B.add(s);
            }
            else
            {
                a.w.play();
                /*JOptionPane.showMessageDialog(null,"Ohoo..!! Gameover..!!");
                System.exit(0);*/
                new z_gameover().setVisible(true);
            }
        }
       
        else
        {
            C.add(s);
            obj.B.add(s);
            
            try {
                FileOutputStream fos = new FileOutputStream("StoreE");
                ObjectOutputStream oos = new ObjectOutputStream(fos);   
                oos.writeObject(C);
                oos.close(); 
            }
            catch(Exception ex) {
                ex.printStackTrace();
            }
            if(C.size()==2)
            {
                a.c.play();
                this.jButton1.setEnabled(true);     
            }
        }
}
    /**
     * Creates new form words_level2
     */
    public z_words_level2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deep = new javax.swing.JLabel();
        cut = new javax.swing.JLabel();
        orange = new javax.swing.JLabel();
        aaple = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/chair.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 182, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/cultural.PNG"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 220, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/dog.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 130, 70));

        deep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/deep.PNG"))); // NOI18N
        deep.setText("jLabel4");
        deep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deepMouseClicked(evt);
            }
        });
        getContentPane().add(deep, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 150, -1));

        cut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/cut.PNG"))); // NOI18N
        cut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cutMouseClicked(evt);
            }
        });
        getContentPane().add(cut, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 220, 130, 70));

        orange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/orange.PNG"))); // NOI18N
        orange.setText("jLabel6");
        orange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orangeMouseClicked(evt);
            }
        });
        getContentPane().add(orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 180, 60));

        aaple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/apple.PNG"))); // NOI18N
        aaple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aapleMouseClicked(evt);
            }
        });
        getContentPane().add(aaple, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 170, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/detail.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 190, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/nextbutton.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 3));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, 653, 190, 90));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("LEVEL 2");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 255, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 210, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 730));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 730));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 730));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 730));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, -1, 730));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aapleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aapleMouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="apple";
        aaple.setBorder(b);
        working2(str);
    }//GEN-LAST:event_aapleMouseClicked

    private void deepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deepMouseClicked
        a.q.play();
        String str;
        str="deep";
        deep.setBorder(b);
        working2(str);// TODO add your handling code here:
    }//GEN-LAST:event_deepMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="dog";
        jLabel3.setBorder(b);
        working2(str);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void orangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeMouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="orange";
        orange.setBorder(b);
        working2(str);
    }//GEN-LAST:event_orangeMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="cultural";
        jLabel2.setBorder(b);
        working2(str);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="detail";
        jLabel8.setBorder(b);
        working2(str);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="chair";
        jLabel1.setBorder(b);
        working2(str);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutMouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="cut";
        cut.setBorder(b);
       working2(str);
    }//GEN-LAST:event_cutMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  next
        //this.setVisible(false);
        new z_words_level3().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(z_words_level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(z_words_level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(z_words_level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(z_words_level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new z_words_level2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaple;
    private javax.swing.JLabel cut;
    private javax.swing.JLabel deep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel orange;
    // End of variables declaration//GEN-END:variables
}
