/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toycathon;

import java.awt.Color;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.BorderFactory;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Paarkavi Saravanan
 */
public class z_words_level1_hard extends javax.swing.JFrame {
    z_audio a=new z_audio();
    MatteBorder b= BorderFactory.createMatteBorder(5,5,5,5,Color.red);
    z_logic obj=new z_logic();
    public void working1(String str){
        obj.A.add(str);
   
    try {
         FileOutputStream fos = new FileOutputStream("StoreH");
         ObjectOutputStream oos = new ObjectOutputStream(fos);   
         oos.writeObject(obj.A);
         oos.close(); 
     }
     catch(Exception ex) {
         ex.printStackTrace();
     }
   if(obj.A.size()==1)
         {
             a.c.play();
             this.jButton1.setEnabled(true);
         }
}
    /**
     * Creates new form words_level1_hard
     */
    public z_words_level1_hard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discrete = new javax.swing.JLabel();
        discreet = new javax.swing.JLabel();
        fair = new javax.swing.JLabel();
        hear1 = new javax.swing.JLabel();
        hear = new javax.swing.JLabel();
        fare = new javax.swing.JLabel();
        heal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        discrete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/discrete.PNG"))); // NOI18N
        discrete.setText("jLabel1");
        discrete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discreteMouseClicked(evt);
            }
        });
        getContentPane().add(discrete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 240, 70));

        discreet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/discreet.PNG"))); // NOI18N
        discreet.setText("jLabel2");
        discreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discreetMouseClicked(evt);
            }
        });
        getContentPane().add(discreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 230, 70));

        fair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/fair.PNG"))); // NOI18N
        fair.setText("jLabel3");
        fair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fairMouseClicked(evt);
            }
        });
        getContentPane().add(fair, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 150, 80));

        hear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/hear.PNG"))); // NOI18N
        hear1.setText("jLabel4");
        hear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hear1MouseClicked(evt);
            }
        });
        getContentPane().add(hear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, 150, 60));

        hear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/hear.PNG"))); // NOI18N
        hear.setText("jLabel5");
        hear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hearMouseClicked(evt);
            }
        });
        getContentPane().add(hear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 150, 70));

        fare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/fare.PNG"))); // NOI18N
        fare.setText("jLabel6");
        fare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fareMouseClicked(evt);
            }
        });
        getContentPane().add(fare, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 170, 70));

        heal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/heal.PNG"))); // NOI18N
        heal.setText("jLabel7");
        heal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healMouseClicked(evt);
            }
        });
        getContentPane().add(heal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 150, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/nextbutton.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 3));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 660, 210, 80));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("LEVEL 1");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 255, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 210, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 730));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, 730));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 730));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 730));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, -1, 730));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void healMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healMouseClicked
        a.q.play();
        String str;
        str="heal";
        heal.setBorder(b);
        working1(str);
    }//GEN-LAST:event_healMouseClicked

    private void discreteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discreteMouseClicked
        a.q.play();
        String str;
        str="discrete";
        discrete.setBorder(b);
        working1(str);
    }//GEN-LAST:event_discreteMouseClicked

    private void fairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fairMouseClicked
        a.q.play();
        String str;
        str="fair";
        fair.setBorder(b);
        working1(str);
    }//GEN-LAST:event_fairMouseClicked

    private void discreetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discreetMouseClicked
       a.q.play();
       String str;
        str="discreet";
        discreet.setBorder(b);
        working1(str);
    }//GEN-LAST:event_discreetMouseClicked

    private void fareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fareMouseClicked
        a.q.play();
        String str;
        str="fare";
        fare.setBorder(b);
        working1(str);
    }//GEN-LAST:event_fareMouseClicked

    private void hear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hear1MouseClicked
        a.q.play();
        String str;
        str="here";
        hear1.setBorder(b);
        working1(str);
    }//GEN-LAST:event_hear1MouseClicked

    private void hearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hearMouseClicked
        a.q.play();
        String str;
        str="hear";
        hear.setBorder(b);
        working1(str);
    }//GEN-LAST:event_hearMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  next
        //this.setVisible(false);
        new z_words_level2_hard().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(z_words_level1_hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(z_words_level1_hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(z_words_level1_hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(z_words_level1_hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new z_words_level1_hard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel discreet;
    private javax.swing.JLabel discrete;
    private javax.swing.JLabel fair;
    private javax.swing.JLabel fare;
    private javax.swing.JLabel heal;
    private javax.swing.JLabel hear;
    private javax.swing.JLabel hear1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
