/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toycathon;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;
import toycathon.z_logic;

/**
 *
 * @author Paarkavi Saravanan
 */
public class z_words_level2_medium extends javax.swing.JFrame {
    z_audio a=new z_audio();
    MatteBorder b= BorderFactory.createMatteBorder(5,5,5,5,Color.red);
    z_logic obj=new z_logic();
    ArrayList<String> C = new ArrayList<String>();
    
    int count=0;
    
    {
    try
    {
    FileInputStream rd=new FileInputStream("StoreM");
    ObjectInputStream rr=new ObjectInputStream(rd);
    C=(ArrayList<String>)rr.readObject();
    rr.close();
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    }
    
    public void working2(String s)
    {
        count++;
        if(count==1)
        {
            if(C.get(0).equals(s))
            {
            obj.B.add(s);
            }
            else
            {
                a.w.play();
                new z_gameover().setVisible(true);
            }
        }
       
        else
        {
            C.add(s);
            obj.B.add(s);
            
            try {
                FileOutputStream fos = new FileOutputStream("StoreM");
                ObjectOutputStream oos = new ObjectOutputStream(fos);   
                oos.writeObject(C);
                oos.close(); 
            }
            catch(Exception ex) {
                ex.printStackTrace();
            }
            if(C.size()==2)
            {
                a.c.play();
                this.jButton1.setEnabled(true);     
            }
        }
    }

    /**
     * Creates new form words_level2_medium
     */
    public z_words_level2_medium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bye = new javax.swing.JLabel();
        ball = new javax.swing.JLabel();
        feedd = new javax.swing.JLabel();
        man = new javax.swing.JLabel();
        buy = new javax.swing.JLabel();
        feed = new javax.swing.JLabel();
        men = new javax.swing.JLabel();
        bowl = new javax.swing.JLabel();
        chick = new javax.swing.JLabel();
        trees = new javax.swing.JLabel();
        stickers = new javax.swing.JLabel();
        tree = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/bye.PNG"))); // NOI18N
        bye.setText("jLabel1");
        bye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                byeMouseClicked(evt);
            }
        });
        getContentPane().add(bye, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 130, 70));

        ball.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/ball.PNG"))); // NOI18N
        ball.setText("jLabel2");
        ball.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ballMouseClicked(evt);
            }
        });
        getContentPane().add(ball, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 140, 60));

        feedd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/feed.PNG"))); // NOI18N
        feedd.setText("jLabel3");
        feedd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feeddMouseClicked(evt);
            }
        });
        getContentPane().add(feedd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, 160, 70));

        man.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/man.PNG"))); // NOI18N
        man.setText("jLabel4");
        man.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manMouseClicked(evt);
            }
        });
        getContentPane().add(man, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 130, 50));

        buy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/buy.PNG"))); // NOI18N
        buy.setText("jLabel5");
        buy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyMouseClicked(evt);
            }
        });
        getContentPane().add(buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 130, 70));

        feed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/feed.PNG"))); // NOI18N
        feed.setText("jLabel6");
        feed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedMouseClicked(evt);
            }
        });
        getContentPane().add(feed, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 160, 60));

        men.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/men.PNG"))); // NOI18N
        men.setText("jLabel7");
        men.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menMouseClicked(evt);
            }
        });
        getContentPane().add(men, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 130, 70));

        bowl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/bowl.PNG"))); // NOI18N
        bowl.setText("jLabel8");
        bowl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bowlMouseClicked(evt);
            }
        });
        getContentPane().add(bowl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 150, 50));

        chick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/chick.PNG"))); // NOI18N
        chick.setText("jLabel9");
        chick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chickMouseClicked(evt);
            }
        });
        getContentPane().add(chick, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, 180, 80));

        trees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/trees.PNG"))); // NOI18N
        trees.setText("jLabel10");
        trees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treesMouseClicked(evt);
            }
        });
        getContentPane().add(trees, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 190, 80));

        stickers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/stickers.PNG"))); // NOI18N
        stickers.setText("jLabel11");
        stickers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stickersMouseClicked(evt);
            }
        });
        getContentPane().add(stickers, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 240, 70));

        tree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/tree.PNG"))); // NOI18N
        tree.setText("jLabel12");
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        getContentPane().add(tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 160, 50));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("LEVEl 2");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 255, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 200, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/nextbutton.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 3));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, 673, 200, 70));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 730));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 730));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 730));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 730));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, -1, 730));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treesMouseClicked
        a.q.play();
        String str;
        str="trees";
        trees.setBorder(b);
        working2(str);
    }//GEN-LAST:event_treesMouseClicked

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
        a.q.play();
        String str;
        str="tree";
        tree.setBorder(b);
        working2(str);
    }//GEN-LAST:event_treeMouseClicked

    private void byeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byeMouseClicked
        a.q.play();
        String str;
        str="bye";
        bye.setBorder(b);
        working2(str);
    }//GEN-LAST:event_byeMouseClicked

    private void ballMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballMouseClicked
        a.q.play();
        String str;
        str="ball";
        ball.setBorder(b);
        working2(str);
    }//GEN-LAST:event_ballMouseClicked

    private void stickersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stickersMouseClicked
        a.q.play();
        String str;
        str="stickers";
        stickers.setBorder(b);
        working2(str);
    }//GEN-LAST:event_stickersMouseClicked

    private void menMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menMouseClicked
        a.q.play();
        String str;
        str="men";
        men.setBorder(b);
        working2(str);
    }//GEN-LAST:event_menMouseClicked

    private void buyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyMouseClicked
        a.q.play();
        String str;
        str="buy";
        buy.setBorder(b);
        working2(str);
    }//GEN-LAST:event_buyMouseClicked

    private void feedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedMouseClicked
        a.q.play();
        String str;
        str="feed";
        feed.setBorder(b);
        working2(str);
    }//GEN-LAST:event_feedMouseClicked

    private void manMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manMouseClicked
        a.q.play();
        String str;
        str="man";
        man.setBorder(b);
        working2(str);
    }//GEN-LAST:event_manMouseClicked

    private void chickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickMouseClicked
        a.q.play();
        String str;
        str="chick";
        chick.setBorder(b);
        working2(str);
    }//GEN-LAST:event_chickMouseClicked

    private void bowlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bowlMouseClicked
        a.q.play();
        String str;
        str="bowl";
        bowl.setBorder(b);
        working2(str);
    }//GEN-LAST:event_bowlMouseClicked

    private void feeddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feeddMouseClicked
        a.q.play();
        String str;
        str="food";
        feedd.setBorder(b);
        working2(str);
    }//GEN-LAST:event_feeddMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  next
        //this.setVisible(false);
        new z_words_level3_medium().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(z_words_level2_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(z_words_level2_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(z_words_level2_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(z_words_level2_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new z_words_level2_medium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ball;
    private javax.swing.JLabel bowl;
    private javax.swing.JLabel buy;
    private javax.swing.JLabel bye;
    private javax.swing.JLabel chick;
    private javax.swing.JLabel feed;
    private javax.swing.JLabel feedd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel man;
    private javax.swing.JLabel men;
    private javax.swing.JLabel stickers;
    private javax.swing.JLabel tree;
    private javax.swing.JLabel trees;
    // End of variables declaration//GEN-END:variables
}
