/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toycathon;
import java.awt.Color;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.BorderFactory;
import javax.swing.border.MatteBorder;
/**
 *
 * @author Paarkavi Saravanan
 */
public class z_words_level1_medium extends javax.swing.JFrame {
    z_audio a=new z_audio();
    MatteBorder b= BorderFactory.createMatteBorder(5,5,5,5,Color.red);
    z_logic obj=new z_logic();
    public void working1(String str){
        obj.A.add(str);
   
    try {
         FileOutputStream fos = new FileOutputStream("StoreM");
         ObjectOutputStream oos = new ObjectOutputStream(fos);   
         oos.writeObject(obj.A);
         oos.close(); 
     }
     catch(Exception ex) {
         ex.printStackTrace();
     }
   if(obj.A.size()==1)
         {
             a.c.play();
             this.jButton1.setEnabled(true);
         }
}

    public z_words_level1_medium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trees = new javax.swing.JLabel();
        tree = new javax.swing.JLabel();
        chick = new javax.swing.JLabel();
        stickers = new javax.swing.JLabel();
        man = new javax.swing.JLabel();
        men = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/trees.PNG"))); // NOI18N
        trees.setText("jLabel1");
        trees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treesMouseClicked(evt);
            }
        });
        getContentPane().add(trees, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 180, 60));

        tree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/tree.PNG"))); // NOI18N
        tree.setText("jLabel2");
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        getContentPane().add(tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 160, 60));

        chick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/chick.PNG"))); // NOI18N
        chick.setText("jLabel3");
        chick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chickMouseClicked(evt);
            }
        });
        getContentPane().add(chick, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 170, 60));

        stickers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/stickers.PNG"))); // NOI18N
        stickers.setText("jLabel4");
        stickers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stickersMouseClicked(evt);
            }
        });
        getContentPane().add(stickers, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 240, 60));

        man.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/man.PNG"))); // NOI18N
        man.setText("jLabel5");
        man.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manMouseClicked(evt);
            }
        });
        getContentPane().add(man, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 530, 130, 60));

        men.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/men.PNG"))); // NOI18N
        men.setText("jLabel6");
        men.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menMouseClicked(evt);
            }
        });
        getContentPane().add(men, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 130, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/nextbutton.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 3));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 660, 200, 80));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("LEVEL 1");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 255, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 220, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 730));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, 730));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 730));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 730));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, -1, 730));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickMouseClicked
        a.q.play();
        String str;
        str="chick";
        chick.setBorder(b);
        working1(str);
    }//GEN-LAST:event_chickMouseClicked

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
        a.q.play();
        String str;
        str="tree";
        tree.setBorder(b);
        working1(str);
    }//GEN-LAST:event_treeMouseClicked

    private void menMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menMouseClicked
        a.q.play();
        String str;
        str="men";
        men.setBorder(b);
        working1(str);
    }//GEN-LAST:event_menMouseClicked

    private void stickersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stickersMouseClicked
        a.q.play();
        String str;
        str="stickers";
        stickers.setBorder(b);
        working1(str);
    }//GEN-LAST:event_stickersMouseClicked

    private void treesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treesMouseClicked
        a.q.play();
        String str;
        str="trees";
        trees.setBorder(b);
        working1(str);
    }//GEN-LAST:event_treesMouseClicked

    private void manMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manMouseClicked
        a.q.play();
        String str;
        str="man";
        man.setBorder(b);
        working1(str);
    }//GEN-LAST:event_manMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  next
        //this.setVisible(false);
        new z_words_level2_medium().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(z_words_level1_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(z_words_level1_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(z_words_level1_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(z_words_level1_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new z_words_level1_medium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chick;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel man;
    private javax.swing.JLabel men;
    private javax.swing.JLabel stickers;
    private javax.swing.JLabel tree;
    private javax.swing.JLabel trees;
    // End of variables declaration//GEN-END:variables
}
