/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toycathon;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Paarkavi Saravanan
 */
public class z_words_level3_medium extends javax.swing.JFrame {
    z_audio a=new z_audio();
    MatteBorder b= BorderFactory.createMatteBorder(5,5,5,5,Color.red);
    z_logic obj=new z_logic();
    ArrayList<String> C2 = new ArrayList<String>();
     int count=0;
    
      
    {
    try
    {
        FileInputStream rd=new FileInputStream("StoreM");
        ObjectInputStream rr=new ObjectInputStream(rd);
        C2=(ArrayList<String>)rr.readObject();
        rr.close();
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    }
    
    public void working3(String s){
        count++;
        if(count<=2)
        {
            if(count==1){
                if(C2.get(0).equals(s)){
                    obj.B.add(s);
                }
                else{
                    a.w.play();
                    new z_gameover().setVisible(true);
                }
            }
            else{
                if(C2.get(1).equals(s))
                {
                    obj.B.add(s);
                }
                else{
                    a.w.play();
                    new z_gameover().setVisible(true);
                }
            }
        }
       else{
            C2.add(s);
            obj.B.add(s);
            try{
            FileOutputStream ff=new FileOutputStream("StoreM");
            ObjectOutputStream oo=new ObjectOutputStream(ff);
            oo.writeObject(C2);
            oo.close();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            if(obj.B.size()==3)
            {
                a.c.play();
                this.jButton1.setEnabled(true);     
            }
        }
    }
    
   
    /**
     * Creates new form words_level3_medium
     */
    public z_words_level3_medium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tree = new javax.swing.JLabel();
        disease = new javax.swing.JLabel();
        feed = new javax.swing.JLabel();
        men = new javax.swing.JLabel();
        buy = new javax.swing.JLabel();
        chick = new javax.swing.JLabel();
        feedd = new javax.swing.JLabel();
        bowl = new javax.swing.JLabel();
        accept = new javax.swing.JLabel();
        eight = new javax.swing.JLabel();
        man = new javax.swing.JLabel();
        trees = new javax.swing.JLabel();
        current = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        election = new javax.swing.JLabel();
        bye = new javax.swing.JLabel();
        ball = new javax.swing.JLabel();
        stickers = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/tree.PNG"))); // NOI18N
        tree.setText("jLabel1");
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        getContentPane().add(tree, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 160, 50));

        disease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/disease.PNG"))); // NOI18N
        disease.setText("jLabel2");
        disease.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diseaseMouseClicked(evt);
            }
        });
        getContentPane().add(disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, 200, 60));

        feed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/feed.PNG"))); // NOI18N
        feed.setText("jLabel3");
        feed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedMouseClicked(evt);
            }
        });
        getContentPane().add(feed, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 150, 60));

        men.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/men.PNG"))); // NOI18N
        men.setText("jLabel4");
        men.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menMouseClicked(evt);
            }
        });
        getContentPane().add(men, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 130, 70));

        buy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/buy.PNG"))); // NOI18N
        buy.setText("jLabel5");
        buy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyMouseClicked(evt);
            }
        });
        getContentPane().add(buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 140, 70));

        chick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/chick.PNG"))); // NOI18N
        chick.setText("jLabel6");
        chick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chickMouseClicked(evt);
            }
        });
        getContentPane().add(chick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 210, 160, 60));

        feedd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/feed.PNG"))); // NOI18N
        feedd.setText("jLabel7");
        feedd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feeddMouseClicked(evt);
            }
        });
        getContentPane().add(feedd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 320, 150, 60));

        bowl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/bowl.PNG"))); // NOI18N
        bowl.setText("jLabel8");
        bowl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bowlMouseClicked(evt);
            }
        });
        getContentPane().add(bowl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 550, 150, 60));

        accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/accept.PNG"))); // NOI18N
        accept.setText("jLabel9");
        accept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acceptMouseClicked(evt);
            }
        });
        getContentPane().add(accept, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 210, 60));

        eight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/eight.PNG"))); // NOI18N
        eight.setText("jLabel10");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 170, 50));

        man.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/man.PNG"))); // NOI18N
        man.setText("jLabel11");
        man.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manMouseClicked(evt);
            }
        });
        getContentPane().add(man, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 790, 140, 50));

        trees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/trees.PNG"))); // NOI18N
        trees.setText("jLabel12");
        trees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treesMouseClicked(evt);
            }
        });
        getContentPane().add(trees, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 190, 50));

        current.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/current.PNG"))); // NOI18N
        current.setText("jLabel13");
        current.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentMouseClicked(evt);
            }
        });
        getContentPane().add(current, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 220, 50));

        weight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/weight.PNG"))); // NOI18N
        weight.setText("jLabel14");
        weight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weightMouseClicked(evt);
            }
        });
        getContentPane().add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 210, 70));

        election.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/election.PNG"))); // NOI18N
        election.setText("jLabel15");
        election.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electionMouseClicked(evt);
            }
        });
        getContentPane().add(election, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 230, 60));

        bye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/bye.PNG"))); // NOI18N
        bye.setText("jLabel16");
        bye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                byeMouseClicked(evt);
            }
        });
        getContentPane().add(bye, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 120, 70));

        ball.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/ball.PNG"))); // NOI18N
        ball.setText("jLabel17");
        ball.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ballMouseClicked(evt);
            }
        });
        getContentPane().add(ball, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, 140, 50));

        stickers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/stickers.PNG"))); // NOI18N
        stickers.setText("jLabel18");
        stickers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stickersMouseClicked(evt);
            }
        });
        getContentPane().add(stickers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 230, 70));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("LEVEL 3");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 255, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 210, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/nextbutton.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 3));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1139, 663, 200, 70));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, -1, 730));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 730));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 730));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 730));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menMouseClicked
        a.q.play();
        String str;
        str="men";
        men.setBorder(b);
        working3(str);
    }//GEN-LAST:event_menMouseClicked

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
         a.q.play();
         String str;
        str="tree";
        tree.setBorder(b);
        working3(str);
    }//GEN-LAST:event_treeMouseClicked

    private void currentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentMouseClicked
        a.q.play();
        String str;
        str="current";
        current.setBorder(b);
        working3(str);
    }//GEN-LAST:event_currentMouseClicked

    private void weightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weightMouseClicked
        a.q.play();
        String str;
        str="weight";
        weight.setBorder(b);
        working3(str);
    }//GEN-LAST:event_weightMouseClicked

    private void electionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electionMouseClicked
        a.q.play();
        String str;
        str="election";
        election.setBorder(b);
        working3(str);
    }//GEN-LAST:event_electionMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
       a.q.play();
       String str;
        str="eight";
        eight.setBorder(b);
        working3(str);
    }//GEN-LAST:event_eightMouseClicked

    private void feedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedMouseClicked
         a.q.play();
         String str;
        str="feed";
        feed.setBorder(b);
        working3(str);
    }//GEN-LAST:event_feedMouseClicked

    private void byeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_byeMouseClicked
        a.q.play();
        String str;
        str="bye";
        bye.setBorder(b);
        working3(str);
    }//GEN-LAST:event_byeMouseClicked

    private void treesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treesMouseClicked
        a.q.play();
        String str;
        str="trees";
        trees.setBorder(b);
        working3(str);
    }//GEN-LAST:event_treesMouseClicked

    private void acceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptMouseClicked
        a.q.play();
        String str;
        str="accept";
        accept.setBorder(b);
        working3(str);
    }//GEN-LAST:event_acceptMouseClicked

    private void feeddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feeddMouseClicked
        a.q.play();
        String str;
        str="food";
        feedd.setBorder(b);
        working3(str);
    }//GEN-LAST:event_feeddMouseClicked

    private void ballMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ballMouseClicked
         a.q.play();
         String str;
        str="ball";
        ball.setBorder(b);
        working3(str);
    }//GEN-LAST:event_ballMouseClicked

    private void chickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickMouseClicked
        
        a.q.play();
        String str;
        str="chick";
        chick.setBorder(b);
        working3(str);
    }//GEN-LAST:event_chickMouseClicked

    private void stickersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stickersMouseClicked
         a.q.play();
         String str;
        str="stickers";
        stickers.setBorder(b);
        working3(str);
    }//GEN-LAST:event_stickersMouseClicked

    private void buyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyMouseClicked
        a.q.play();
        String str;
        str="buy";
        buy.setBorder(b);
        working3(str);
    }//GEN-LAST:event_buyMouseClicked

    private void bowlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bowlMouseClicked
        a.q.play();
        String str;
        str="bowl";
        bowl.setBorder(b);
        working3(str);
    }//GEN-LAST:event_bowlMouseClicked

    private void manMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manMouseClicked
        a.q.play();
        String str;
        str="man";
        man.setBorder(b);
        working3(str);
    }//GEN-LAST:event_manMouseClicked

    private void diseaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diseaseMouseClicked
        a.q.play();
        String str;
        str="disease";
        disease.setBorder(b);
        working3(str);
    }//GEN-LAST:event_diseaseMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  next
        //this.setVisible(false);
        new z_won_word().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(z_words_level3_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(z_words_level3_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(z_words_level3_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(z_words_level3_medium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new z_words_level3_medium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accept;
    private javax.swing.JLabel ball;
    private javax.swing.JLabel bowl;
    private javax.swing.JLabel buy;
    private javax.swing.JLabel bye;
    private javax.swing.JLabel chick;
    private javax.swing.JLabel current;
    private javax.swing.JLabel disease;
    private javax.swing.JLabel eight;
    private javax.swing.JLabel election;
    private javax.swing.JLabel feed;
    private javax.swing.JLabel feedd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel man;
    private javax.swing.JLabel men;
    private javax.swing.JLabel stickers;
    private javax.swing.JLabel tree;
    private javax.swing.JLabel trees;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
