/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toycathon;

import java.awt.Color;
import java.util.ArrayList;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.BorderFactory;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Paarkavi Saravanan
 */
public class z_words_level1 extends javax.swing.JFrame {
    z_audio a=new z_audio();
       
    MatteBorder b= BorderFactory.createMatteBorder(5,5,5,5,Color.red);
    z_logic obj=new z_logic();
    public void working1(String str){
        obj.A.add(str);
   
    try {
         FileOutputStream fos = new FileOutputStream("StoreE");
         ObjectOutputStream oos = new ObjectOutputStream(fos);   
         oos.writeObject(obj.A);
         oos.close(); 
     }
     catch(Exception ex) {
         ex.printStackTrace();
     }
   if(obj.A.size()==1)
         {
             a.c.play();
             this.jButton1.setEnabled(true);
         }
}

    /**
     * Creates new form words_level1
     */
    public z_words_level1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deep = new javax.swing.JLabel();
        cultural = new javax.swing.JLabel();
        cut = new javax.swing.JLabel();
        chair = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/deep.PNG"))); // NOI18N
        deep.setText("jLabel1");
        deep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deepMouseClicked(evt);
            }
        });
        getContentPane().add(deep, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 150, 70));

        cultural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/cultural.PNG"))); // NOI18N
        cultural.setText("jLabel2");
        cultural.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                culturalMouseClicked(evt);
            }
        });
        getContentPane().add(cultural, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 226, 60));

        cut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/cut.PNG"))); // NOI18N
        cut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cutMouseClicked(evt);
            }
        });
        getContentPane().add(cut, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 130, 70));

        chair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/chair.PNG"))); // NOI18N
        chair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chairMouseClicked(evt);
            }
        });
        getContentPane().add(chair, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 160, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/nextbutton.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 3));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 620, 219, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("LEVEL 1");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 255, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, 730));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 730));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, -1, 730));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, -1, 730));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deepMouseClicked
        a.q.play();
        String str;
        str="deep";
        deep.setBorder(b);
        working1(str);
       
    }//GEN-LAST:event_deepMouseClicked

    private void culturalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_culturalMouseClicked
        a.q.play();
        String str;
        str="cultural";
        cultural.setBorder(b);
        working1(str);
    }//GEN-LAST:event_culturalMouseClicked

    private void cutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutMouseClicked
        a.q.play();
        String str;
        str="cut";
        cut.setBorder(b);
        working1(str);
    }//GEN-LAST:event_cutMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  next
        //this.setVisible(false);
        new z_words_level2().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chairMouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="chair";
        chair.setBorder(b);
        working1(str);
    }//GEN-LAST:event_chairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(z_words_level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(z_words_level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(z_words_level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(z_words_level1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new z_words_level1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chair;
    private javax.swing.JLabel cultural;
    private javax.swing.JLabel cut;
    private javax.swing.JLabel deep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}

