/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toycathon;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Paarkavi Saravanan
 */
public class z_words_level3_hard extends javax.swing.JFrame {

    /**
     * Creates new form words_level3_hard
     */
    public z_words_level3_hard() {
        
        initComponents();
    }
    z_audio a=new z_audio();
    MatteBorder b= BorderFactory.createMatteBorder(5,5,5,5,Color.red);
    z_logic obj=new z_logic();
    ArrayList<String> C2 = new ArrayList<String>();
     int count=0;
    
    {
    try
    {
        FileInputStream rd=new FileInputStream("StoreH");
        ObjectInputStream rr=new ObjectInputStream(rd);
        C2=(ArrayList<String>)rr.readObject();
        rr.close();
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    }
    
    public void working3(String s){
        count++;
        if(count<=2)
        {
            if(count==1){
                if(C2.get(0).equals(s)){
                    obj.B.add(s);
                }
                else{
                    a.w.play();
                    new z_gameover().setVisible(true);
                }
            }
            else{
                if(C2.get(1).equals(s))
                {
                    obj.B.add(s);
                }
                else{
                    a.w.play();
                    new z_gameover().setVisible(true);
                }
            }
        }
       else{
            C2.add(s);
            obj.B.add(s);
            try{
            FileOutputStream ff=new FileOutputStream("StoreH");
            ObjectOutputStream oo=new ObjectOutputStream(ff);
            oo.writeObject(C2);
            oo.close();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            if(obj.B.size()==3)
            {
                a.c.play();
                this.jButton1.setEnabled(true);     
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hear1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        hear = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/discreet.PNG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 230, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/alouded.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 200, 60));

        hear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/hear.PNG"))); // NOI18N
        hear1.setText("jLabel3");
        hear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hear1MouseClicked(evt);
            }
        });
        getContentPane().add(hear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 150, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/allowed.PNG"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 220, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/bare.PNG"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 260, 150, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/dual.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 140, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/counsil.PNG"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 220, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/best.PNG"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 160, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/reel.PNG"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, 130, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/real.PNG"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 140, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/worst.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 200, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/bad.PNG"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 120, -1));

        hear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/hear.PNG"))); // NOI18N
        hear.setText("jLabel15");
        hear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hearMouseClicked(evt);
            }
        });
        getContentPane().add(hear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 70));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/heal.PNG"))); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 430, 150, 70));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/bear.PNG"))); // NOI18N
        jLabel17.setText("jLabel17");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 150, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/bat.PNG"))); // NOI18N
        jLabel18.setText("jLabel18");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 120, 60));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/counsel.PNG"))); // NOI18N
        jLabel19.setText("jLabel19");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 200, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/fare.PNG"))); // NOI18N
        jLabel20.setText("jLabel20");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, 160, 70));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/fair.PNG"))); // NOI18N
        jLabel21.setText("jLabel21");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 160, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/discrete.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 580, 240, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/nextbutton.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255), 3));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 683, 180, 60));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 255, 255));
        jLabel22.setText("LEVEL 3");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 255, 0)));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 220, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 730));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 730));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 730));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 730));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, -1, 730));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toycathon/gif.gif"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  next
        //this.setVisible(false);
        new z_wonhard().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hearMouseClicked
        // TODO add your handling code here:
        a.q.play();
        String str;
        str="hear";
        hear.setBorder(b);
        working3(str);
    }//GEN-LAST:event_hearMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here: alouded
        a.q.play();
        String str;
        str="alouded";
        jLabel2.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here: allowed
        a.q.play();
        String str;
        str="allowed";
        jLabel4.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here: discreet
        a.q.play();
        String str;
        str="discreet";
        jLabel1.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here: real
        a.q.play();
        String str;
        str="real";
        jLabel12.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here: bad
        a.q.play();
        String str;
        str="bad";
        jLabel14.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void hear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hear1MouseClicked
        // TODO add your handling code here: here
        a.q.play();
        String str;
        str="here";
        hear1.setBorder(b);
        working3(str);
    }//GEN-LAST:event_hear1MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here: best
        a.q.play();
        String str;
        str="best";
        jLabel8.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here: counsel
        a.q.play();
        String str;
        str="counsel";
        jLabel19.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here: council
        a.q.play();
        String str;
        str="council";
        jLabel7.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here: dual
        a.q.play();
        String str;
        str="dual";
        jLabel6.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here: reel
        a.q.play();
        String str;
        str="reel";
        jLabel11.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here: worst
        a.q.play();
        String str;
        str="worst";
        jLabel13.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here: fare
        a.q.play();
        String str;
        str="fare";
        jLabel20.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here: bat
        a.q.play();
        String str;
        str="bat";
        jLabel18.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here: bare
        a.q.play();
        String str;
        str="bare";
        jLabel5.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here: fair
        a.q.play();
        String str;
        str="fair";
        jLabel21.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here: bear
        a.q.play();
        String str;
        str="bear";
        jLabel17.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here: heal
        a.q.play();
        String str;
        str="heal";
        jLabel16.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here: discrete
        a.q.play();
        String str;
        str="discrete";
        jLabel3.setBorder(b);
        working3(str);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(z_words_level3_hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(z_words_level3_hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(z_words_level3_hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(z_words_level3_hard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new z_words_level3_hard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hear;
    private javax.swing.JLabel hear1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
